[package]
name = "sqlx-test"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
sqlx = { default-features = false, path = ".." }
sqlx-rt = { path = "../sqlx-rt", features = ["capture-awaits"] }
backtrace = "0.3.50"
futures = "0.3.5"
env_logger = "0.7.1"
log = "0.4.11"
dotenv = "0.15.0"
anyhow = "1.0.26"
async-std = { version = "1.5.0", features = [ "attributes" ] }
tokio = { version = "0.2.13", features = [ "full" ] }
